- hosts: localhost
  vars:
    BASE_URL: "{{ lookup('ansible.builtin.env', 'HOME') }}/Documents/Projects/AnsibleTest/"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    OTTERDEV: "otterdev-site"
    USER: "{{ lookup('env', 'USER') }}"
    YOU: "arkar"
  # pre_tasks:
  #   - name: Running  "pacman -Sy"
  #     become: true
  #     pacman:
  #       update_cache: yes

  tasks:
    - include: tasks/pretasks.yml
    - include: tasks/zsh.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    # - include: tasks/otter-repo.yml
    - include: tasks/test.yml
