- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  ansible.builtin.debug:
    msg: [ 🦦 Info ] Installing nodejs and npm
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  ansible.builtin.debug:
    msg: [ 🦦 Info ] Adding npmjs prefix
  tags:
    - install
    - node

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
    - install
    - node

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags:
    - install
    - node
    - npm-path

- name: Install latest version of Node
  shell: "npx n latest"
  ansible.builtin.debug:
    msg: [ 🦦 Info ] Installing latest version of node
    - install
    - node
